### ISSUE TITLE
Educational Page

### ISSUE THREAD

**Issue by Insax** [savetheinternetinfo/website#10] opened 2018-06-22 05:27 UTC
Add Videos Newspapers / Blogs with good explanations of the problem to a subpage - contact Public Relations to get your information

**Comment by Pacerino** [comment] 2018-06-28 18:49
Currently on hold because missing external informations

**Comment by Pacerino** [comment] 2018-07-01 13:47
Issue is held because information and use case are missing.
Will hold agreement with overall coordination.

**Comment by kellerrennkadse** [comment] 2018-07-06 08:30
That's basically a duplicate of #70 right?

**Comment by kellerrennkadse** [comment] 2018-07-17 18:51
This is already done (even if its gross af, but PR refuses to provide data to fix this.)

**Closed by kellerrennkadse** 2018-07-17 18:51 UTC
Labels: External, enhancement
